"""Performance-ready extensions for the Opticable E50 provisioning profile.

Default state favors throughput and access reliability:
- FastTrack remains enabled.
- Conservative RAW prefiltering is enabled.
- QoS mangle/queue rules are created but disabled.
- Per-tenant simple queues generated by the base profile are disabled.

This lets Tikcentral switch an installed router to a fairness/QoS profile later
without rebuilding the configuration onsite.
"""

from app import provisioning


_base_default_config_script = provisioning.default_config_script


def _performance_block(wan_down: int, wan_up: int) -> str:
    # Leave headroom so, when enabled later, the router owns the bottleneck
    # instead of an ISP queue. This profile is dormant by default.
    qos_down = max(10, int(wan_down * 0.95))
    qos_up = max(10, int(wan_up * 0.95))

    return f'''
# ----------------------------------------------------------
# E50 performance-ready profile
# Default: RAW prefilter ON, FastTrack ON, QoS OFF
# ----------------------------------------------------------

# Conservative RAW prefiltering. These rules reject impossible/malformed WAN
# traffic before connection tracking. Do not drop RFC1918/CGNAT here because
# DHCP/upstream networks may legitimately use private addressing.
:if ([:len [/ip/firewall/address-list find where list="Opticable_BAD_SRC" and address="127.0.0.0/8"]] = 0) do={{ /ip/firewall/address-list add list=Opticable_BAD_SRC address=127.0.0.0/8 comment="Loopback cannot arrive from wire" }}
:if ([:len [/ip/firewall/address-list find where list="Opticable_BAD_SRC" and address="224.0.0.0/4"]] = 0) do={{ /ip/firewall/address-list add list=Opticable_BAD_SRC address=224.0.0.0/4 comment="Multicast cannot be a source" }}
:if ([:len [/ip/firewall/address-list find where list="Opticable_BAD_SRC" and address="240.0.0.0/4"]] = 0) do={{ /ip/firewall/address-list add list=Opticable_BAD_SRC address=240.0.0.0/4 comment="Reserved source range" }}
:if ([:len [/ip/firewall/address-list find where list="Opticable_BAD_SRC" and address="255.255.255.255"]] = 0) do={{ /ip/firewall/address-list add list=Opticable_BAD_SRC address=255.255.255.255 comment="Invalid source broadcast" }}

:if ([:len [/ip/firewall/raw find where comment="Opticable RAW DHCP"]] = 0) do={{ /ip/firewall/raw add chain=prerouting action=accept protocol=udp src-port=68 dst-port=67 comment="Opticable RAW DHCP" }}
:if ([:len [/ip/firewall/raw find where comment="Opticable RAW LAN fast accept"]] = 0) do={{ /ip/firewall/raw add chain=prerouting action=accept in-interface-list=LAN comment="Opticable RAW LAN fast accept" }}
:if ([:len [/ip/firewall/raw find where comment="Opticable RAW bad source"]] = 0) do={{ /ip/firewall/raw add chain=prerouting action=drop in-interface-list=WAN src-address-list=Opticable_BAD_SRC comment="Opticable RAW bad source" }}
:if ([:len [/ip/firewall/raw find where comment="Opticable RAW UDP port zero"]] = 0) do={{ /ip/firewall/raw add chain=prerouting action=drop in-interface-list=WAN protocol=udp port=0 comment="Opticable RAW UDP port zero" }}
:if ([:len [/ip/firewall/raw find where comment="Opticable RAW TCP port zero"]] = 0) do={{ /ip/firewall/raw add chain=prerouting action=drop in-interface-list=WAN protocol=tcp port=0 comment="Opticable RAW TCP port zero" }}
:if ([:len [/ip/firewall/raw find where comment="Opticable RAW WAN DNS to router"]] = 0) do={{ /ip/firewall/raw add chain=prerouting action=drop in-interface-list=WAN protocol=udp dst-port=53 comment="Opticable RAW WAN DNS to router" }}

# Queue types are definitions only and consume no forwarding CPU while unused.
:if ([:len [/queue/type find where name="OPT-CAKE-UP"]] = 0) do={{ /queue/type add name=OPT-CAKE-UP kind=cake cake-ack-filter=filter cake-diffserv=diffserv4 cake-flowmode=dual-srchost cake-nat=yes cake-overhead=50 cake-rtt-scheme=internet }}
:if ([:len [/queue/type find where name="OPT-CAKE-DOWN"]] = 0) do={{ /queue/type add name=OPT-CAKE-DOWN kind=cake cake-diffserv=diffserv4 cake-flowmode=dual-dsthost cake-nat=yes cake-overhead=50 cake-rtt-scheme=internet }}
:if ([:len [/queue/type find where name="OPT-FQ-CODEL"]] = 0) do={{ /queue/type add name=OPT-FQ-CODEL kind=fq-codel fq-codel-ecn=no fq-codel-limit=1000 }}

# QoS packet marking - prepared but disabled while FastTrack is the active
# performance profile.
:if ([:len [/ip/firewall/mangle find where comment="Opticable QoS mark upload"]] = 0) do={{ /ip/firewall/mangle add chain=prerouting in-interface-list=LAN packet-mark=no-mark action=mark-packet new-packet-mark=OPT-QOS-UP passthrough=no disabled=yes comment="Opticable QoS mark upload" }}
:if ([:len [/ip/firewall/mangle find where comment="Opticable QoS mark download"]] = 0) do={{ /ip/firewall/mangle add chain=prerouting in-interface-list=WAN packet-mark=no-mark action=mark-packet new-packet-mark=OPT-QOS-DOWN passthrough=no disabled=yes comment="Opticable QoS mark download" }}

# Optional DSCP classification rules. They are intentionally dormant; Tikcentral
# can selectively enable them after measuring CPU and loaded latency.
:if ([:len [/ip/firewall/mangle find where comment="Opticable QoS Teams WebRTC"]] = 0) do={{ /ip/firewall/mangle add chain=prerouting in-interface-list=TENANT_VLAN protocol=udp dst-port=3478-3481 action=change-dscp new-dscp=34 passthrough=yes disabled=yes comment="Opticable QoS Teams WebRTC" }}
:if ([:len [/ip/firewall/mangle find where comment="Opticable QoS small QUIC"]] = 0) do={{ /ip/firewall/mangle add chain=prerouting protocol=udp dst-port=443 connection-bytes=0-2000000 action=change-dscp new-dscp=40 passthrough=yes disabled=yes comment="Opticable QoS small QUIC" }}
:if ([:len [/ip/firewall/mangle find where comment="Opticable QoS small HTTPS"]] = 0) do={{ /ip/firewall/mangle add chain=prerouting protocol=tcp dst-port=443 connection-bytes=0-2000000 action=change-dscp new-dscp=40 passthrough=yes disabled=yes comment="Opticable QoS small HTTPS" }}
:if ([:len [/ip/firewall/mangle find where comment="Opticable QoS bulk TCP"]] = 0) do={{ /ip/firewall/mangle add chain=prerouting protocol=tcp connection-bytes=20000000-0 action=change-dscp new-dscp=8 passthrough=yes disabled=yes comment="Opticable QoS bulk TCP" }}
:if ([:len [/ip/firewall/mangle find where comment="Opticable QoS bulk UDP"]] = 0) do={{ /ip/firewall/mangle add chain=prerouting protocol=udp connection-bytes=20000000-0 action=change-dscp new-dscp=8 passthrough=yes disabled=yes comment="Opticable QoS bulk UDP" }}
:if ([:len [/ip/firewall/mangle find where comment="Opticable QoS gaming"]] = 0) do={{ /ip/firewall/mangle add chain=prerouting protocol=udp port=30000-45000 action=change-dscp new-dscp=32 passthrough=yes disabled=yes comment="Opticable QoS gaming" }}

# WAN-agnostic queue trees. Enable only after disabling FastTrack and enabling
# the two OPT-QOS packet-mark rules above.
:if ([:len [/queue/tree find where name="OPT-QOS-UPLOAD"]] = 0) do={{ /queue/tree add name=OPT-QOS-UPLOAD parent=global packet-mark=OPT-QOS-UP max-limit={qos_up}M queue=OPT-CAKE-UP disabled=yes comment="Opticable QoS upload - {qos_up}M" }}
:if ([:len [/queue/tree find where name="OPT-QOS-DOWNLOAD"]] = 0) do={{ /queue/tree add name=OPT-QOS-DOWNLOAD parent=global packet-mark=OPT-QOS-DOWN max-limit={qos_down}M queue=OPT-CAKE-DOWN disabled=yes comment="Opticable QoS download - {qos_down}M" }}

:put "Performance profile ready: FastTrack active; RAW active; QoS/mangle staged disabled"
'''.strip()


def performance_ready_default_config_script(site_name: str, vlan_count: int, lan_count: int,
                                            wan_down: int, wan_up: int, tenant_down: int,
                                            tenant_up: int, vlan_parent: str) -> str:
    script = _base_default_config_script(
        site_name, vlan_count, lan_count, wan_down, wan_up,
        tenant_down, tenant_up, vlan_parent,
    )

    # Tenant caps are part of the dormant QoS profile. With FastTrack enabled,
    # active simple queues would be misleading because FastTracked traffic
    # bypasses them. Stage them disabled instead.
    script = script.replace(
        'comment="Opticable tenant cap"',
        'disabled=yes comment="Opticable tenant cap - QoS profile disabled"',
    )

    block = _performance_block(wan_down, wan_up)
    head, sep, tail = script.rpartition("\n}")
    if not sep:
        return script + "\n" + block + "\n"
    return head + "\n\n" + block + sep + tail


def install():
    provisioning.default_config_script = performance_ready_default_config_script
