"""Opticable fresh-router provisioning and encrypted admin credentials.

Web routes live in app.enrollment. Database schema lives in app.migrations.
"""

from cryptography.fernet import Fernet, InvalidToken

from app import main as core
from app import migrations
from app import settings


def ensure_schema():
    migrations.migrate()


def _fernet():
    key = settings.PROVISIONING_KEY.encode()
    if not key:
        raise RuntimeError("TIKCENTRAL_PROVISIONING_KEY is not configured")
    return Fernet(key)


def _encrypt(value: str) -> str:
    return _fernet().encrypt(value.encode()).decode()


def _decrypt(value: str) -> str:
    if not value:
        return ""
    try:
        return _fernet().decrypt(value.encode()).decode()
    except (InvalidToken, ValueError):
        return ""


def get_admin_credentials() -> tuple[str, str]:
    ensure_schema()
    with core.db() as conn:
        row = conn.execute(
            "SELECT admin_username,admin_password_enc FROM provisioning_settings WHERE id=1"
        ).fetchone()
    return (row["admin_username"] or "", _decrypt(row["admin_password_enc"] or ""))


def set_admin_credentials(username: str, password: str):
    if not username or len(username) > 64:
        raise ValueError("invalid personal username")
    if not password or len(password) > 256:
        raise ValueError("invalid personal password")
    ensure_schema()
    with core.db() as conn:
        conn.execute(
            "UPDATE provisioning_settings SET admin_username=?,admin_password_enc=? WHERE id=1",
            (username, _encrypt(password)),
        )


def _ros(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$")


def personal_admin_block(username: str, password: str) -> str:
    if not username or not password:
        return ""
    user = _ros(username)
    secret = _ros(password)
    return f'''
# Personal Opticable administrator - reconcile, do not duplicate
:if ([:len [/user find where name="{user}"]] = 0) do={{
    /user add name="{user}" password="{secret}" group=full disabled=no comment="Opticable personal admin"
}} else={{
    /user set [find where name="{user}"] password="{secret}" group=full disabled=no comment="Opticable personal admin"
}}
'''.strip()


def default_config_script(site_name: str, vlan_count: int, lan_count: int,
                          wan_down: int, wan_up: int, tenant_down: int,
                          tenant_up: int, vlan_parent: str) -> str:
    """Generate the Opticable fresh-router baseline.

    Intended only after RouterOS/RouterBOOT update and a no-defaults reset.
    DHCP on ether1 remains the fallback; Bell VLAN35 + disabled PPPoE are staged.
    """
    site = _ros(site_name)
    parent = _ros(vlan_parent)
    qblock = ""
    if tenant_down > 0 and tenant_up > 0:
        qblock = f'''
# Optional per-tenant caps
:for n from=1 to={vlan_count} do={{
    :local target ("172.16." . $n . ".0/24")
    :local qname ("Tenant-VLAN" . ($n * 10))
    :if ([:len [/queue/simple find where name=$qname]] = 0) do={{
        /queue/simple add name=$qname target=$target max-limit={tenant_up}M/{tenant_down}M comment="Opticable tenant cap"
    }}
}}
'''

    return f'''# ==========================================================
# Opticable Multi-Tenant hEX E50 - FRESH ROUTER BASELINE
# Site: {site_name}
# Generated by Tikcentral
# WARNING: intended for a new/default router, not an active site.
# ==========================================================
{{
/system identity set name="{site}"
/system clock set time-zone-name=America/Toronto
/system ntp client set enabled=yes
:if ([:len [/system ntp client servers find where address="0.ca.pool.ntp.org"]] = 0) do={{ /system ntp client servers add address=0.ca.pool.ntp.org }}

# Interface lists
:if ([:len [/interface/list find where name="WAN"]] = 0) do={{ /interface/list add name=WAN }}
:if ([:len [/interface/list find where name="LAN"]] = 0) do={{ /interface/list add name=LAN }}
:if ([:len [/interface/list find where name="TENANT_VLAN"]] = 0) do={{ /interface/list add name=TENANT_VLAN comment="Opticable tenant VLANs" }}

# WAN: DHCP active + Bell VLAN35 + disabled dummy PPPoE profile
:if ([:len [/interface/vlan find where name="ISP-VLAN35"]] = 0) do={{ /interface/vlan add name=ISP-VLAN35 interface=ether1 vlan-id=35 comment="Bell Internet VLAN" }}
:if ([:len [/ip/dhcp-client find where interface=ether1]] = 0) do={{ /ip/dhcp-client add interface=ether1 add-default-route=yes default-route-distance=2 use-peer-dns=no disabled=no comment="Default WAN DHCP" }}
:if ([:len [/interface/pppoe-client find where name="PPPOE-OUT-01"]] = 0) do={{
    /interface/pppoe-client add name=PPPOE-OUT-01 interface=ISP-VLAN35 user="CHANGE@bellnet.ca" password="CHANGE_ME" add-default-route=yes default-route-distance=1 use-peer-dns=no disabled=yes comment="Bell PPPoE - enter credentials onsite"
}}
:if ([:len [/interface/list/member find where list=WAN and interface=ether1]] = 0) do={{ /interface/list/member add list=WAN interface=ether1 }}
:if ([:len [/interface/list/member find where list=WAN and interface=ISP-VLAN35]] = 0) do={{ /interface/list/member add list=WAN interface=ISP-VLAN35 }}
:if ([:len [/interface/list/member find where list=WAN and interface=PPPOE-OUT-01]] = 0) do={{ /interface/list/member add list=WAN interface=PPPOE-OUT-01 }}

# Tenant VLANs: VLAN10 -> 172.16.1.0/24, VLAN20 -> 172.16.2.0/24, etc.
:for n from=1 to={vlan_count} do={{
    :local vid ($n * 10)
    :local vname ("VLAN" . $vid)
    :local poolname ("Pool_172.16." . $n . ".0")
    :local gw ("172.16." . $n . ".1")
    :local net ("172.16." . $n . ".0/24")
    :local range ("172.16." . $n . ".10-172.16." . $n . ".250")
    :if ([:len [/interface/vlan find where name=$vname]] = 0) do={{ /interface/vlan add name=$vname interface="{parent}" vlan-id=$vid }}
    :if ([:len [/interface/list/member find where list=LAN and interface=$vname]] = 0) do={{ /interface/list/member add list=LAN interface=$vname }}
    :if ([:len [/interface/list/member find where list=TENANT_VLAN and interface=$vname]] = 0) do={{ /interface/list/member add list=TENANT_VLAN interface=$vname }}
    :if ([:len [/ip/address find where interface=$vname and address=($gw . "/24")]] = 0) do={{ /ip/address add address=($gw . "/24") interface=$vname }}
    :if ([:len [/ip/pool find where name=$poolname]] = 0) do={{ /ip/pool add name=$poolname ranges=$range }}
    :local dhcpname ("Dhcp_" . $vname)
    :if ([:len [/ip/dhcp-server find where name=$dhcpname]] = 0) do={{ /ip/dhcp-server add name=$dhcpname interface=$vname address-pool=$poolname disabled=no }}
    :if ([:len [/ip/dhcp-server/network find where address=$net]] = 0) do={{ /ip/dhcp-server/network add address=$net gateway=$gw dns-server=1.1.1.1 }}
}}

# Physical LANs: ether2..ether{lan_count + 1}
:for n from=2 to={lan_count + 1} do={{
    :local ifname ("ether" . $n)
    :local gw ("10." . $n . ".0.1")
    :local net ("10." . $n . ".0.0/24")
    :local poolname ("MGMT-" . $ifname)
    :if ([:len [/interface/list/member find where list=LAN and interface=$ifname]] = 0) do={{ /interface/list/member add list=LAN interface=$ifname }}
    :if ([:len [/ip/address find where interface=$ifname and address=($gw . "/24")]] = 0) do={{ /ip/address add address=($gw . "/24") interface=$ifname }}
    :if ([:len [/ip/pool find where name=$poolname]] = 0) do={{ /ip/pool add name=$poolname ranges=("10." . $n . ".0.20-10." . $n . ".0.254") }}
    :if ([:len [/ip/dhcp-server find where name=$poolname]] = 0) do={{ /ip/dhcp-server add name=$poolname interface=$ifname address-pool=$poolname disabled=no }}
    :if ([:len [/ip/dhcp-server/network find where address=$net]] = 0) do={{ /ip/dhcp-server/network add address=$net gateway=$gw dns-server=1.1.1.1 }}
}}

# DNS/NAT
/ip/dns set allow-remote-requests=no servers=1.1.1.1
:if ([:len [/ip/firewall/nat find where comment="Opticable WAN NAT"]] = 0) do={{ /ip/firewall/nat add chain=srcnat action=masquerade out-interface-list=WAN comment="Opticable WAN NAT" }}

# Balanced forwarding profile
:if ([:len [/ip/firewall/filter find where comment="Opticable FastTrack"]] = 0) do={{ /ip/firewall/filter add chain=forward action=fasttrack-connection connection-state=established,related hw-offload=yes comment="Opticable FastTrack" }}
:if ([:len [/ip/firewall/filter find where comment="Opticable forward established"]] = 0) do={{ /ip/firewall/filter add chain=forward action=accept connection-state=established,related,untracked comment="Opticable forward established" }}
:if ([:len [/ip/firewall/filter find where comment="Opticable forward invalid"]] = 0) do={{ /ip/firewall/filter add chain=forward action=drop connection-state=invalid comment="Opticable forward invalid" }}
:if ([:len [/ip/firewall/filter find where comment="Opticable WAN forward drop"]] = 0) do={{ /ip/firewall/filter add chain=forward action=drop connection-state=new connection-nat-state=!dstnat in-interface-list=WAN comment="Opticable WAN forward drop" }}

# Router input baseline - Tikcentral enrollment prepends management exceptions.
:if ([:len [/ip/firewall/filter find where comment="Opticable input established"]] = 0) do={{ /ip/firewall/filter add chain=input action=accept connection-state=established,related,untracked comment="Opticable input established" }}
:if ([:len [/ip/firewall/filter find where comment="Opticable input invalid"]] = 0) do={{ /ip/firewall/filter add chain=input action=drop connection-state=invalid comment="Opticable input invalid" }}
:if ([:len [/ip/firewall/filter find where comment="Opticable LAN ICMP"]] = 0) do={{ /ip/firewall/filter add chain=input action=accept in-interface-list=LAN protocol=icmp comment="Opticable LAN ICMP" }}
:if ([:len [/ip/firewall/filter find where comment="Opticable non-LAN input drop"]] = 0) do={{ /ip/firewall/filter add chain=input action=drop in-interface-list=!LAN comment="Opticable non-LAN input drop" }}

# Service defaults
/ip/service set [find where name="telnet"] disabled=yes
/ip/service set [find where name="ftp"] disabled=yes
/ip/smb set enabled=no
/tool/bandwidth-server set enabled=no
/ip/firewall/service-port set tftp disabled=yes
/ip/firewall/service-port set h323 disabled=yes
/ip/firewall/service-port set sip disabled=yes
/ip/firewall/service-port set pptp disabled=yes
/ip/cloud set ddns-enabled=yes
/ipv6/settings set disable-ipv6=yes

# Requested nominal WAN profile: {wan_down}M down / {wan_up}M up
{qblock}
:put "Opticable default configuration complete; continuing with Tikcentral enrollment"
}}
'''
